#include "vehicle_var.hh"

Aerodynamics_var::Aerodynamics_var() : VECTOR_INIT(XCP, 3) {}

ACT_var::ACT_var() : VECTOR_INIT(Q_RCS, 6), VECTOR_INIT(Q_TVC, 6) {}

EarthEnvironment_var::EarthEnvironment_var()
    : VECTOR_INIT(GRAVG, 3), MATRIX_INIT(TEI, 3, 3), VECTOR_INIT(VBAB, 3), VECTOR_INIT(VAED, 3) {}

DM_var::DM_var()
    : MATRIX_INIT(TBI, 3, 3),
      MATRIX_INIT(TBID, 3, 3),
      VECTOR_INIT(TBI_Q, 4),
      VECTOR_INIT(TBID_Q, 4),
      MATRIX_INIT(TBD, 3, 3),
      VECTOR_INIT(TBDQ, 4),
      VECTOR_INIT(VBAB, 3),
      MATRIX_INIT(WEII_skew, 3, 3),
      VECTOR_INIT(SBIIP, 3),
      VECTOR_INIT(VBIIP, 3),
      VECTOR_INIT(SBII, 3),
      VECTOR_INIT(VBII, 3),
      VECTOR_INIT(ABII, 3),
      VECTOR_INIT(ABIB, 3),
      VECTOR_INIT(SBEE, 3),
      VECTOR_INIT(VBEE, 3),
      VECTOR_INIT(ABEE, 3),
      VECTOR_INIT(SBEE_old, 3),
      VECTOR_INIT(VBEE_old, 3),
      VECTOR_INIT(ABEE_old, 3),
      VECTOR_INIT(JBII, 3),
      VECTOR_INIT(JBEE, 3),
      MATRIX_INIT(TDI, 3, 3),
      MATRIX_INIT(TGI, 3, 3),
      VECTOR_INIT(VBED, 3),
      VECTOR_INIT(FSPB, 3),
      VECTOR_INIT(NEXT_ACC, 3),
      MATRIX_INIT(TDE, 3, 3),
      VECTOR_INIT(VBII_old, 3),
      VECTOR_INIT(WEII, 3),
      VECTOR_INIT(WBII, 3),
      VECTOR_INIT(WBEB, 3),
      VECTOR_INIT(WBIB, 3),
      VECTOR_INIT(WBIBD, 3),
      MATRIX_INIT(TVD, 3, 3),
      VECTOR_INIT(SBEE_test, 3),
      VECTOR_INIT(VBEE_test, 3),
      VECTOR_INIT(ABEE_test, 3),
      MATRIX_INIT(TLI, 3, 3),
      VECTOR_INIT(LT_euler, 3),
      VECTOR_INIT(TBLQ, 4),
      VECTOR_INIT(ABID, 3),
      VECTOR_INIT(FAPB, 3),
      VECTOR_INIT(FAP, 3),
      VECTOR_INIT(FMB, 3),
      VECTOR_INIT(FMAB, 3),
      VECTOR_INIT(Q_G, 6),
      VECTOR_INIT(Q_Aero, 6),
      VECTOR_INIT(rhoC_1, 3),
      MATRIX_INIT(I1, 3, 3),
      VECTOR_INIT(ddrP_1, 3),
      VECTOR_INIT(ddang_1, 3),
      VECTOR_INIT(dang_1, 3),
      VECTOR_INIT(ddrhoC_1, 3),
      VECTOR_INIT(p_b1_ga, 3),
      VECTOR_INIT(p_b1_be, 3),
      VECTOR_INIT(f, 6),
      VECTOR_INIT(gamma_b1_q1, 3),
      VECTOR_INIT(gamma_b1_q2, 3),
      VECTOR_INIT(gamma_b1_q3, 3),
      VECTOR_INIT(beta_b1_q4, 3),
      VECTOR_INIT(beta_b1_q5, 3),
      VECTOR_INIT(beta_b1_q6, 3) {}

Prop_var::Prop_var() : VECTOR_INIT(XCG, 3), MATRIX_INIT(IBBB, 3, 3) {}

Sensor_var::Sensor_var() : VECTOR_INIT(FSPCB, 3),
                           VECTOR_INIT(EFSPB, 3),
                           VECTOR_INIT(EWALKA, 3),
                           VECTOR_INIT(EMISA, 3),
                           VECTOR_INIT(ESCALA, 3),
                           VECTOR_INIT(EBIASA, 3),
                           VECTOR_INIT(ITA1_A, 3),
                           VECTOR_INIT(ITA2_A, 3),
                           VECTOR_INIT(BETA_A, 3),
                           VECTOR_INIT(EUG, 3),
                           VECTOR_INIT(EWG, 3),
                           VECTOR_INIT(EWALKG, 3),
                           VECTOR_INIT(EUNBG, 3),
                           VECTOR_INIT(EMISG, 3),
                           VECTOR_INIT(ESCALG, 3),
                           VECTOR_INIT(EBIASG, 3),
                           VECTOR_INIT(ITA1_G, 3),
                           VECTOR_INIT(ITA2_G, 3),
                           VECTOR_INIT(BETA_G, 3),
                           VECTOR_INIT(WBICB, 3),
                           VECTOR_INIT(EWBIB, 3),
                           VECTOR_INIT(PHI, 3),
                           VECTOR_INIT(DELTA_VEL, 3),
                           VECTOR_INIT(WBISB, 3),
                           VECTOR_INIT(WBISB_old, 3),
                           VECTOR_INIT(DELTA_ALPHA, 3),
                           VECTOR_INIT(DELTA_ALPHA_old, 3),
                           VECTOR_INIT(ALPHA, 3),
                           VECTOR_INIT(FSPSB, 3),
                           VECTOR_INIT(FSPSB_old, 3),
                           VECTOR_INIT(cross2_old, 3),
                           VECTOR_INIT(VEL, 3) {}
