#ifndef __MISSION_EVENTS_DEFINE_H__
#define __MISSION_EVENTS_DEFINE_H__
typedef enum __ENUM_FLIGHT_EVENT_CODE {
    FLIGHT_EVENT_CODE_EMPTY = 0,
    FLIGHT_EVENT_CODE_LIFTOFF = 1,
    FLIGHT_EVENT_CODE_S3_SEPERATION = 2,
    FLIGHT_EVENT_CODE_S3_CONTROL_ON = 3,
    FLIGHT_EVENT_CODE_S3_IGNITION = 4,
    FLIGHT_EVENT_FAIRING_JETTSION = 5,
    FLIGHT_EVENT_CODE_CONTROL_OFF = 6,
    FLIGHT_EVENT_CODE_HOT_STAGING = 7,
    FLIGHT_EVENT_PITCH_DOWN_PHASE_I = 8,
    FLIGHT_EVENT_PITCH_DOWN_PHASE_II = 9,
    FLIGHT_EVENT_AOA_CONTROL = 10,
    FLIGHT_EVENT_PAYLOAD_DEPLOY = 11,
    FLIGHT_EVENT_CODE_S2_ROLL_CONTROL = 12,
    FLIGHT_EVENT_TVC_CONTROL_ON = 13,
    FLIGHT_EVENT_CODE_S1_SEPERATION = 14,
    FLIGHT_EVENT_S2_CONTROL_ON = 15,
    FLIGHT_EVENT_CODE_S2_SEPERATION = 16,
    FLIGHT_EVENT_CODE_S1_CONTROL_ON = 17,
    FLIGHT_EVENT_CODE_UECO = 18,
    FLIGHT_EVENT_CODE_MAX_NUM
} ENUM_FLIGHT_EVENT_CODE;
#endif  //  __MISSION_EVENTS_DEFINE_H__